### ISSUE TITLE
kofax/rpa-roboserver has grown 2x on v11

### ISSUE THREAD

**Issue by kasperbrandenburg-schibsted** [KofaxRPA/KofaxRPA#1]
Hi

Why has the container for kofax/rpa-roboserver grown from 1.57 to +3GB between two builds on v11.4. This seems to be an error,
and its impacting our build-time as pulling twice the data is actually noticeable.

![image](https://user-images.githubusercontent.com/102357366/223434231-990c0f0e-a58a-48cb-8c70-ed6b74b1d427.png)

**Comment by TungstenRPA** [comment]
Hi Kasper,
11.4.0.1 changed roboserver to not have root access anymore, due to security requests from some customers. This was done in the Docker image by running **chown** (change ownership) on all of the files, and this doubled the size of the image.
The developers are aware of this. For now you could rebuild the image yourself following [this article](https://stackoverflow.com/questions/30085621/why-does-chown-increase-size-of-docker-image) to not double the image size.

David
